# Generated by Django 4.2.4 on 2023-08-31 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='img_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
